### ISSUE TITLE
getting a weird error

### ISSUE THREAD

**Issue by TonySwearingen** [learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal#13]
### Canvas Link

https://learning.flatironschool.com/courses/5166/assignments/159346?module_item_id=341675

### Concern

 /home/tony/.rbenv/versions/3.0.1/lib/ruby/3.0.0/fileutils.rb:206:in `mkdir_p': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/git/wip/reference.rb:18:in `initialize'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/git/wip/base.rb:27:in `new'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/git/wip/base.rb:27:in `initialize'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/git.rb:13:in `new'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/git.rb:13:in `wip'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/reporter.rb:61:in `report'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/reporter.rb:13:in `report'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/runner.rb:49:in `report_and_clean'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/runner.rb:22:in `block in run'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/runner.rb:21:in `fork'
        from /home/tony/.ruby/gems/learn-test-3.3.1/lib/learn_test/runner.rb:21:in `run'
        from /home/tony/.ruby/gems/learn-test-3.3.1/bin/learn-test:73:in `<top (required)>'
        from /home/tony/.ruby/bin/learn-test:23:in `load'
        from /home/tony/.ruby/bin/learn-test:23:in `<main>'

### Additional Context

Ran learn got a weird error

**Comment by lizbur10** [comment]
Hi @TonySwearingen ! Thanks for raising this issue.

It looks as though this error is related to your environment setup, specifically, your Ruby version. You can try going back through the process for setting up Ruby and see if that clears the error:

For Mac: https://github.com/learn-co-curriculum/phase-0-macos-env-ruby
For Windows: https://github.com/learn-co-curriculum/phase-0-wsl2-env-ruby

Otherwise, if you have not yet started the program, you can get help by posting a question in the #js-prework-support Slack channel. 

If you have started the program, you can either:

- Reach out to your instructor, or
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
