### ISSUE TITLE
Testing file has been removed or the directions are not clear.

### ISSUE THREAD

**Issue by foreverluiscastro** [learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal#21]
### Canvas Link

https://learning.flatironschool.com/courses/5055/assignments/152486?confetti=true&submitted=0

### Concern

A student in [2021-11-SENG-PREWORK-SOFTWARE-ENGINEERING-PREWORK] told me they are unable to run `learn test` and I explained that it is because this repo does not contain a testing file. It is described in the attached lesson as something they should be able to do and receive a result for.

### Suggested Changes

Restructure the `Using the learn-co Gem` part of this lesson to be descriptive of what this process would feel like (so much so that a new student can reference the `Using the learn-co Gem` info to use the gem in future lessons) or add in a testing file so that what is being described in the lesson will actually happen for the student.

**Comment by lizbur10** [comment]
Hi Luis! This lesson no longer includes a Using the learn-co Gem section. The student is in a pretty old prework cohort, so their Canvas instance has been disassociated from the blueprint. (This is because there was a major update to prework a few months ago that would have caused breaking changes for current students.) 

Unfortunately, there's nothing I can really do to fix the problem for this student/cohort, but it should not be an issue for students in more recent cohorts.

Many thanks! 💙
