### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by SealTechh** [learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal#23]
### Canvas Link

https://learning.flatironschool.com/courses/6042/pages/configuring-the-flatiron-student-portal?module_item_id=449739

### Concern

When I typed "learn whoami" (without quote) in the Ubuntu application, it displayed "learn: command not found"

**Comment by lizbur10** [comment]
Hi @Sealajoke - sorry to hear you've run into an issue. 

The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support. To get help with this, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

**Comment by SealTechh** [comment]
Thanks
I have got it. 
I re-ran everything starting from learn-co

And it works perfectly

**Comment by SealTechh** [comment]
> Hi @Sealajoke - sorry to hear you've run into an issue. 
> 
> The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support. To get help with this, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Thanks so much sir
I have re-ran everything from learn-co

And it works perfectly fine
